In [14]:
# Entendendo a função Apply

import pandas as pd
import numpy as np

# configurando o arrendondamento em 2 casas decimais
pd.options.display.float_format = '{:,.2f}'.format

valor_apostado = np.array([10, 30, 20, 20, 10, 20]) 
odds_apostadas = np.array([1.8, 2.20, 2.05, 2.75, 1.75, 2.50])
lista_de_apostas = np.array(['Atlético - MG', 'Cruzeiro', 'Palmeiras - 0.75', 'Mais de 2,5 Gols', 'Cartões Amarelos + 5', 'Cantos + 12,5'])

apostas_df = pd.DataFrame({'Valor apostado':valor_apostado, 'Odds apostadas':odds_apostadas, 'Apostas':lista_de_apostas})

apostas_df['lucro_potencial'] = (apostas_df['Odds apostadas'] - 1) * apostas_df['Valor apostado']

apostas_df['lucro_potencial'] = (apostas_df['Odds apostadas'] - 1) * apostas_df['Valor apostado']

apostas_df['prob_aprox'] = 1 / apostas_df['Odds apostadas']

apostas_df = apostas_df[['Apostas', 'Odds apostadas', 'Valor apostado', 'lucro_potencial', 'prob_aprox']]

display(apostas_df) # podia nao usar o display mas é melhor usar pq sem usar pode n funcionar se tiver muitos dados

,Apostas,Odds apostadas,Valor apostado,lucro_potencial,prob_aprox
0,Atlético - MG,1.80,10,8.00,0.56
1,Cruzeiro,2.20,30,36.00,0.45
2,Palmeiras - 0.75,2.05,20,21.00,0.49
3,"Mais de 2,5 Gols",2.75,20,35.00,0.36
4,Cartões Amarelos + 5,1.75,10,7.50,0.57
5,"Cantos + 12,5",2.50,20,30.00,0.40

In [6]:
# para dobrar o valor apostado eu poderia fazer:

apostas_df['aposta_dobrada'] = apostas_df['Valor apostado'] * 2
display(apostas_df)

,Apostas,Odds apostadas,Valor apostado,lucro_potencial,prob_aprox,aposta_dobrada
0,Atlético - MG,1.80,10,8.00,0.56,20
1,Cruzeiro,2.20,30,36.00,0.45,60
2,Palmeiras - 0.75,2.05,20,21.00,0.49,40
3,"Mais de 2,5 Gols",2.75,20,35.00,0.36,40
4,Cartões Amarelos + 5,1.75,10,7.50,0.57,20
5,"Cantos + 12,5",2.50,20,30.00,0.40,40

In [12]:
# mas posso usar o "apply"

def dobrar_aposta(x):
    '''multiplica o valor de x por 2'''
    return x * 2

In [7]:
del apostas_df['aposta_dobrada']
display(apostas_df)

,Apostas,Odds apostadas,Valor apostado,lucro_potencial,prob_aprox
0,Atlético - MG,1.80,10,8.00,0.56
1,Cruzeiro,2.20,30,36.00,0.45
2,Palmeiras - 0.75,2.05,20,21.00,0.49
3,"Mais de 2,5 Gols",2.75,20,35.00,0.36
4,Cartões Amarelos + 5,1.75,10,7.50,0.57
5,"Cantos + 12,5",2.50,20,30.00,0.40

In [15]:
# agora que temos nossa função podemos fazer como segue
# lembrando que pra esse caso específico seria mais simples da primeira maneira
# mas pra outros casos o método apply é mais indicado e facilita bastante

# dobrando a aposta através do método apply


apostas_df['aposta_dobrada'] = apostas_df['Valor apostado'].apply(dobrar_aposta)
display(apostas_df)

,Apostas,Odds apostadas,Valor apostado,lucro_potencial,prob_aprox,aposta_dobrada
0,Atlético - MG,1.80,10,8.00,0.56,20
1,Cruzeiro,2.20,30,36.00,0.45,60
2,Palmeiras - 0.75,2.05,20,21.00,0.49,40
3,"Mais de 2,5 Gols",2.75,20,35.00,0.36,40
4,Cartões Amarelos + 5,1.75,10,7.50,0.57,20
5,"Cantos + 12,5",2.50,20,30.00,0.40,40

In [22]:
np.random.uniform()

0.5664182607210172

In [29]:
# assim ele gera o mesmo número aleatório para a coluna num_ale
apostas_df['num_ale'] = np.random.uniform()
display(apostas_df)

,Apostas,Odds apostadas,Valor apostado,lucro_potencial,prob_aprox,aposta_dobrada,num_ale
0,Atlético - MG,1.80,10,8.00,0.56,20,0.80
1,Cruzeiro,2.20,30,36.00,0.45,60,0.80
2,Palmeiras - 0.75,2.05,20,21.00,0.49,40,0.80
3,"Mais de 2,5 Gols",2.75,20,35.00,0.36,40,0.80
4,Cartões Amarelos + 5,1.75,10,7.50,0.57,20,0.80
5,"Cantos + 12,5",2.50,20,30.00,0.40,40,0.80

In [37]:
# assim os números aleatórios são diferentes
# vamos usar funções lambda ou funções anônimas

apostas_df['num_ale'] = ''
apostas_df['num_ale'] = apostas_df['num_ale'].apply(lambda x: np.random.uniform())
display(apostas_df)

,Apostas,Odds apostadas,Valor apostado,lucro_potencial,prob_aprox,aposta_dobrada,num_ale
0,Atlético - MG,1.80,10,8.00,0.56,20,0.69
1,Cruzeiro,2.20,30,36.00,0.45,60,0.67
2,Palmeiras - 0.75,2.05,20,21.00,0.49,40,0.46
3,"Mais de 2,5 Gols",2.75,20,35.00,0.36,40,0.88
4,Cartões Amarelos + 5,1.75,10,7.50,0.57,20,0.92
5,"Cantos + 12,5",2.50,20,30.00,0.40,40,0.16

In [39]:
# agora vamos usar o apply não apenas em linhas de uma coluna mas nas linhas das colunas informadas
# se faz assim quando queremos usar mais de uma coluna (variável) nas operações

apostas_df['resultado'] = apostas_df.apply(lambda row: 'ganha' if row['num_ale'] <= row['prob_aprox'] else 'perdida', axis = 1)
display(apostas_df)

,Apostas,Odds apostadas,Valor apostado,lucro_potencial,prob_aprox,aposta_dobrada,num_ale,resultado
0,Atlético - MG,1.80,10,8.00,0.56,20,0.69,perdida
1,Cruzeiro,2.20,30,36.00,0.45,60,0.67,perdida
2,Palmeiras - 0.75,2.05,20,21.00,0.49,40,0.46,ganha
3,"Mais de 2,5 Gols",2.75,20,35.00,0.36,40,0.88,perdida
4,Cartões Amarelos + 5,1.75,10,7.50,0.57,20,0.92,perdida
5,"Cantos + 12,5",2.50,20,30.00,0.40,40,0.16,ganha

In [41]:
# verificando o lucro e o prejuízo

def gerar_resultado(val_apostado, luc_potencial, resultado):
    '''retorna o valor após a aposta quanto de lucro ou prejuízo'''
    if resultado == 'ganha':
        lucro_preju = luc_potencial
    else:
        lucro_preju = val_apostado * (-1)
    return lucro_preju

In [43]:
apostas_df['lucro_prejuizo'] = apostas_df.apply(lambda row: gerar_resultado(row['Valor apostado'], row['lucro_potencial'], row['resultado']), axis = 1)
display(apostas_df)

,Apostas,Odds apostadas,Valor apostado,lucro_potencial,prob_aprox,aposta_dobrada,num_ale,resultado,lucro_prejuizo
0,Atlético - MG,1.80,10,8.00,0.56,20,0.69,perdida,-10.00
1,Cruzeiro,2.20,30,36.00,0.45,60,0.67,perdida,-30.00
2,Palmeiras - 0.75,2.05,20,21.00,0.49,40,0.46,ganha,21.00
3,"Mais de 2,5 Gols",2.75,20,35.00,0.36,40,0.88,perdida,-20.00
4,Cartões Amarelos + 5,1.75,10,7.50,0.57,20,0.92,perdida,-10.00
5,"Cantos + 12,5",2.50,20,30.00,0.40,40,0.16,ganha,30.00