In [0]:
import pandas as pd
import numpy as np
from joblib import Parallel, delayed

In [0]:
dfs = pd.read_html(f'https://www.worldfootball.net/schedule/eng-premier-league-2019-2020-spieltag/2', header=0)

In [3]:
len(dfs)

6

In [4]:
dfs[0]

Empty DataFrame
Columns: [Unnamed: 0, 2019/2020  2018/2019  2017/2018  2016/2017  2015/2016  2014/2015  2013/2014  2012/2013  2011/2012  2010/2011  2009/2010  2008/2009  2007/2008  2006/2007  2005/2006  2004/2005  2003/2004  2002/2003  2001/2002  2000/2001  1999/2000  1998/1999  1997/1998  1996/1997  1995/1996  1994/1995  1993/1994  1992/1993  1991/1992  1990/1991  1989/1990  1988/1989  1987/1988  1986/1987  1985/1986  1984/1985  1983/1984  1982/1983  1981/1982  1980/1981  1979/1980  1978/1979  1977/1978  1976/1977  1975/1976  1974/1975  1973/1974  1972/1973  1971/1972  1970/1971  1969/1970  1968/1969  1967/1968  1966/1967  1965/1966  1964/1965  1963/1964  1962/1963  1961/1962  1960/1961  1959/1960  1958/1959  1957/1958  1956/1957  1955/1956  1954/1955  1953/1954  1952/1953  1951/1952  1950/1951  1949/1950  1948/1949  1947/1948  1946/1947  1938/1939  1937/1938  1936/1937  1935/1936  1934/1935  1933/1934  1932/1933  1931/1932  1930/1931  1929/1930  1928/1929  1927/1928  1926/1927  1925/1926  1924/1925  1923/1924  1922/1923  1921/1922  1920/1921  1919/1920  1914/1915  1913/1914  1912/1913  1911/1912  1910/1911  1909/1910  1908/1909  1907/1908  1906/1907  1905/1906  1904/1905  1903/1904  1902/1903  1901/1902  1900/1901  1899/1900  1898/1899  1897/1898  1896/1897  1895/1896  1894/1895  1893/1894  1892/1893  1891/1892  1890/1891  1889/1890  1888/1889, Unnamed: 2, Unnamed: 3, Unnamed: 4, 1. Round  2. Round  3. Round  4. Round  5. Round  6. Round  7. Round  8. Round  9. Round  10. Round  11. Round  12. Round  13. Round  14. Round  15. Round  16. Round  17. Round  18. Round  19. Round  20. Round  21. Round  22. Round  23. Round  24. Round  25. Round  26. Round  27. Round  28. Round  29. Round  30. Round  31. Round  32. Round  33. Round  34. Round  35. Round  36. Round  37. Round  38. Round, Unnamed: 6]
Index: []

In [5]:
dfs[1]

   17/08/2019  12:30  ... Unnamed: 6 Unnamed: 7
0         NaN  15:00  ...        NaN        NaN
1         NaN  15:00  ...        NaN        NaN
2         NaN  15:00  ...        NaN        NaN
3         NaN  15:00  ...        NaN        NaN
4         NaN  15:00  ...        NaN        NaN
5         NaN  17:30  ...        NaN        NaN
6  18/08/2019  14:00  ...        NaN        NaN
7         NaN  16:30  ...        NaN        NaN
8  19/08/2019  20:00  ...        NaN        NaN

[9 rows x 8 columns]

In [6]:
dfs[3] # na posição 4 tem a informação que eu quero

       #  Team                   Team.1  M.  W  D  L goals  Dif.  Pt.
0    1.0   NaN             Liverpool FC   2  2  0  0   6:2     4    6
1    2.0   NaN               Arsenal FC   2  2  0  0   3:1     2    6
2    3.0   NaN          Manchester City   2  1  1  0   7:2     5    4
3    4.0   NaN        Manchester United   2  1  1  0   5:1     4    4
4    5.0   NaN   Brighton & Hove Albion   2  1  1  0   4:1     3    4
5    6.0   NaN        Tottenham Hotspur   2  1  1  0   5:3     2    4
6    7.0   NaN          AFC Bournemouth   2  1  1  0   3:2     1    4
7    8.0   NaN         Sheffield United   2  1  1  0   2:1     1    4
8    9.0   NaN               Everton FC   2  1  1  0   1:0     1    4
9   10.0   NaN               Burnley FC   2  1  0  1   4:2     2    3
10  11.0   NaN             Norwich City   2  1  0  1   4:5    -1    3
11  12.0   NaN           Leicester City   2  0  2  0   1:1     0    2
12   NaN   NaN  Wolverhampton Wanderers   2  0  2  0   1:1     0    2
13  14.0   NaN           Crystal Palace   2  0  1  1   0:1    -1    1
14  15.0   NaN               Chelsea FC   2  0  1  1   1:5    -4    1
15  16.0   NaN          West Ham United   2  0  1  1   1:6    -5    1
16  17.0   NaN              Aston Villa   2  0  0  2   2:5    -3    0
17  18.0   NaN         Newcastle United   2  0  0  2   1:4    -3    0
18  19.0   NaN           Southampton FC   2  0  0  2   1:5    -4    0
19  20.0   NaN               Watford FC   2  0  0  2   0:4    -4    0

In [0]:
# acima foi apenas uma demostraçao de como obter os dados. Agora vamos fazer para pegar varios atributos

def get_table(current_round,max_rounds,league,season,flag):
  dfs = pd.read_html(f'https://www.worldfootball.net/schedule/{league}-{season}-{flag}{current_round}', header=0)
  df = dfs[3]
  # agora vamos apagar a coluna "Team" que aqui não interessa
  df.drop(['Team'], inplace=True, axis=1)

  df.rename(index=str, columns={'#':'pos', 'Team.1':'team', 'M.':'current_round', 'W':'win',
                                'D':'draw', 'L':'loss', 'goals':'goals', 'Dif.':'goals_diff', 'Pt.':'points_for'}, inplace=True)
 
  aux = df['goals'].str.split(':', n=1, expand=True)
  df['goals_for'] = aux[0]
  df['goals_against'] = aux[1]
  df.drop(columns = ['goals'], inplace=True)
  df = df.apply(pd.to_numeric, errors='ignore')
  df['pos'] = pd.to_numeric(df.index) + 1
  df['max_rounds'] = max_rounds
  df['rounds_left'] = df['max_rounds'] - df['current_round']
  df['possible_points'] = df['current_round'] * 3
  df['performance'] = np.round((df['points_for'] / df['possible_points']) * 100, 2)
  df['performance'].replace(np.inf, df['points_for'], inplace=True)
  df.fillna(value={'performance':0}, inplace=True)
  df['total_possible_points'] = df['points_for'] + (df['rounds_left'] * 3)
  df['goals_for_against_ratio'] = df['goals_for'] / df['goals_against']
  df['goals_for_against_ratio'].replace(np.inf, df['goals_for'], inplace=True)
  df.fillna(value={'goals_for_against_ratio':0}, inplace=True)
  df['goals_for_against_ratio'] = np.round(df['goals_for_against_ratio'], 3)
  df['league'] = league
  df['season'] = season
  columns = ['pos', 'team', 'current_round', 'max_rounds', 'rounds_left', 'win', 'loss', 'draw',
             'goals_for', 'goals_against', 'goals_diff', 'goals_for_against_ratio', 'points_for', 'possible_points',
            'total_possible_points', 'performance', 'league', 'season']
  df = df[columns]
  return df

In [0]:
def get_league(max_rounds, league, season, flag):
    table_list = Parallel(n_jobs=38, verbose=0, backend='threading')(delayed(get_table)(current_round, max_rounds, league, season, flag) for current_round in range(1, max_rounds + 1))
    final_table = pd.concat(table_list, ignore_index=True)
    return final_table

In [0]:
def increment_season(season):
  if '-' in season:
    season_years = season.split('-')
    first_year = int(season_years[0]) + 1
    second_year = int(season_years[1]) + 1
    next_season = str(first_year) + '-' + str(second_year)
    return next_season
  else:
    season_year = int(season) + 1
    next_season = str(season_year)
    return next_season

In [0]:
def get_all_leagues(league_dict):
  list_all_seasons = []
  for key in league_dict.keys():
    if (key == 'bra-serie-a') or (key == 'bra-serie-b'):
      while(league_dict[key][0]) != '2019':
        flag = 'spieltag/'
        print(key)
        print(league_dict[key][0])
        table = get_league(league_dict[key][1], key, league_dict[key][0], flag)
        league_dict[key][0] = increment_season(league_dict[key][0])
        list_all_seasons.append(table)
        print('Done!')
    else:
      while(league_dict[key][0]) != '2019-2020':
        if (key == 'esp-primera-division') and (league_dict[key][0] == '2016-2017'):
          flag = 'spieltag_2/'
          print(key)
          print(league_dict[key][0])
          table = get_league(league_dict[key][1], key, league_dict[key][0], flag)
          league_dict[key][0] = increment_season(league_dict[key][0])
          list_all_seasons.append(table)
          print('Done!')
        else:
          flag = 'spieltag/'
          print(key)
          print(league_dict[key][0])
          table = get_league(league_dict[key][1], key, league_dict[key][0], flag)
          league_dict[key][0] = increment_season(league_dict[key][0])
          list_all_seasons.append(table)
          print('Done!')
  final_table = pd.concat(list_all_seasons, ignore_index=True)
  return final_table

In [0]:
league_dict = {'eng-premier-league':['1995-1996', 38], 'esp-primera-division':['1997-1998', 38],
               'fra-ligue-1':['2002-2003', 38], 'bundesliga':['1995-1996', 34],
               'ita-serie-a':['2004-2005', 38], 'ned-eredivisie':['1995-1996', 34],
               'bra-serie-a':['2006', 38], 'bra-serie-b':['2011', 38]}

In [0]:
def add_final_points(df):
  df.loc[((df.index == 98550) | (df.index == 98564)) & (df['team'] == 'Grêmio Prudente'), ['team']] = 'Grêmio Barueri - SP'
  df.loc[((df.index == 96999) | (df.index == 97006)), ['current_round', 'rounds_left', 'loss']] = [(38, 0, 10), (38, 0, 12)]
  unique_leagues = df['league'].unique()
  dfs = []
  for loop_league in unique_leagues:
    unique_seasons = df[df['league'] == loop_league]['season'].unique()
    for season_loop in unique_seasons:
      df_of_season = df[(df['league'] == loop_league) & (df['season'] == season_loop)]
      last_round = np.max(df_of_season['current_round'])
      last_round_df = df_of_season[df_of_season['current_round'] == last_round]
      df_of_season = df_of_season.merge(last_round_df[['team', 'points_for']], how='left', on='team') 
      dfs.append(df_of_season)
  final_df = pd.concat(dfs)
  final_df.rename(index=str, columns={'points_for_x':'points_for', 'points_for_y':'final_points'}, inplace=True)
  return final_df

In [13]:
get_table(1, 38, 'eng-premier-league', '2018-2019', 'spieltag/')

    pos                     team  ...              league     season
0     1             Liverpool FC  ...  eng-premier-league  2018-2019
1     2               Chelsea FC  ...  eng-premier-league  2018-2019
2     3          AFC Bournemouth  ...  eng-premier-league  2018-2019
3     4           Crystal Palace  ...  eng-premier-league  2018-2019
4     5          Manchester City  ...  eng-premier-league  2018-2019
5     6               Watford FC  ...  eng-premier-league  2018-2019
6     7        Manchester United  ...  eng-premier-league  2018-2019
7     8        Tottenham Hotspur  ...  eng-premier-league  2018-2019
8     9               Everton FC  ...  eng-premier-league  2018-2019
9    10  Wolverhampton Wanderers  ...  eng-premier-league  2018-2019
10   11               Burnley FC  ...  eng-premier-league  2018-2019
11   12           Southampton FC  ...  eng-premier-league  2018-2019
12   13           Leicester City  ...  eng-premier-league  2018-2019
13   14         Newcastle United  ...  eng-premier-league  2018-2019
14   15               Arsenal FC  ...  eng-premier-league  2018-2019
15   16   Brighton & Hove Albion  ...  eng-premier-league  2018-2019
16   17             Cardiff City  ...  eng-premier-league  2018-2019
17   18                Fulham FC  ...  eng-premier-league  2018-2019
18   19        Huddersfield Town  ...  eng-premier-league  2018-2019
19   20          West Ham United  ...  eng-premier-league  2018-2019

[20 rows x 18 columns]

In [14]:
final_dataframe = get_all_leagues(league_dict)

eng-premier-league
1995-1996
Done!
eng-premier-league
1996-1997
Done!
eng-premier-league
1997-1998
Done!
eng-premier-league
1998-1999
Done!
eng-premier-league
1999-2000
Done!
eng-premier-league
2000-2001
Done!
eng-premier-league
2001-2002
Done!
eng-premier-league
2002-2003
Done!
eng-premier-league
2003-2004
Done!
eng-premier-league
2004-2005
Done!
eng-premier-league
2005-2006
Done!
eng-premier-league
2006-2007
Done!
eng-premier-league
2007-2008
Done!
eng-premier-league
2008-2009
Done!
eng-premier-league
2009-2010
Done!
eng-premier-league
2010-2011
Done!
eng-premier-league
2011-2012
Done!
eng-premier-league
2012-2013
Done!
eng-premier-league
2013-2014
Done!
eng-premier-league
2014-2015
Done!
eng-premier-league
2015-2016
Done!
eng-premier-league
2016-2017
Done!
eng-premier-league
2017-2018
Done!
eng-premier-league
2018-2019
Done!
esp-primera-division
1997-1998
Done!
esp-primera-division
1998-1999
Done!
esp-primera-division
1999-2000
Done!
esp-primera-division
2000-2001
Done!
esp-primera-division
2001-2002
Done!
esp-primera-division
2002-2003
Done!
esp-primera-division
2003-2004
Done!
esp-primera-division
2004-2005
Done!
esp-primera-division
2005-2006
Done!
esp-primera-division
2006-2007
Done!
esp-primera-division
2007-2008
Done!
esp-primera-division
2008-2009
Done!
esp-primera-division
2009-2010
Done!
esp-primera-division
2010-2011
Done!
esp-primera-division
2011-2012
Done!
esp-primera-division
2012-2013
Done!
esp-primera-division
2013-2014
Done!
esp-primera-division
2014-2015
Done!
esp-primera-division
2015-2016
Done!
esp-primera-division
2016-2017
Done!
esp-primera-division
2017-2018
Done!
esp-primera-division
2018-2019
Done!
fra-ligue-1
2002-2003
Done!
fra-ligue-1
2003-2004
Done!
fra-ligue-1
2004-2005
Done!
fra-ligue-1
2005-2006
Done!
fra-ligue-1
2006-2007
Done!
fra-ligue-1
2007-2008
Done!
fra-ligue-1
2008-2009
Done!
fra-ligue-1
2009-2010
Done!
fra-ligue-1
2010-2011
Done!
fra-ligue-1
2011-2012
Done!
fra-ligue-1
2012-2013
Done!
fra-ligue-1
2013-2014
Done!
fra-ligue-1
2014-2015
Done!
fra-ligue-1
2015-2016
Done!
fra-ligue-1
2016-2017
Done!
fra-ligue-1
2017-2018
Done!
fra-ligue-1
2018-2019
Done!
bundesliga
1995-1996
Done!
bundesliga
1996-1997
Done!
bundesliga
1997-1998
Done!
bundesliga
1998-1999
Done!
bundesliga
1999-2000
Done!
bundesliga
2000-2001
Done!
bundesliga
2001-2002
Done!
bundesliga
2002-2003
Done!
bundesliga
2003-2004
Done!
bundesliga
2004-2005
Done!
bundesliga
2005-2006
Done!
bundesliga
2006-2007
Done!
bundesliga
2007-2008
Done!
bundesliga
2008-2009
Done!
bundesliga
2009-2010
Done!
bundesliga
2010-2011
Done!
bundesliga
2011-2012
Done!
bundesliga
2012-2013
Done!
bundesliga
2013-2014
Done!
bundesliga
2014-2015
Done!
bundesliga
2015-2016
Done!
bundesliga
2016-2017
Done!
bundesliga
2017-2018
Done!
bundesliga
2018-2019
Done!
ita-serie-a
2004-2005
Done!
ita-serie-a
2005-2006
Done!
ita-serie-a
2006-2007
Done!
ita-serie-a
2007-2008
Done!
ita-serie-a
2008-2009
Done!
ita-serie-a
2009-2010
Done!
ita-serie-a
2010-2011
Done!
ita-serie-a
2011-2012
Done!
ita-serie-a
2012-2013
Done!
ita-serie-a
2013-2014
Done!
ita-serie-a
2014-2015
Done!
ita-serie-a
2015-2016
Done!
ita-serie-a
2016-2017
Done!
ita-serie-a
2017-2018
Done!
ita-serie-a
2018-2019
Done!
ned-eredivisie
1995-1996
Done!
ned-eredivisie
1996-1997
Done!
ned-eredivisie
1997-1998
Done!
ned-eredivisie
1998-1999
Done!
ned-eredivisie
1999-2000
Done!
ned-eredivisie
2000-2001
Done!
ned-eredivisie
2001-2002
Done!
ned-eredivisie
2002-2003
Done!
ned-eredivisie
2003-2004
Done!
ned-eredivisie
2004-2005
Done!
ned-eredivisie
2005-2006
Done!
ned-eredivisie
2006-2007
Done!
ned-eredivisie
2007-2008
Done!
ned-eredivisie
2008-2009
Done!
ned-eredivisie
2009-2010
Done!
ned-eredivisie
2010-2011
Done!
ned-eredivisie
2011-2012
Done!
ned-eredivisie
2012-2013
Done!
ned-eredivisie
2013-2014
Done!
ned-eredivisie
2014-2015
Done!
ned-eredivisie
2015-2016
Done!
ned-eredivisie
2016-2017
Done!
ned-eredivisie
2017-2018
Done!
ned-eredivisie
2018-2019
Done!
bra-serie-a
2006
Done!
bra-serie-a
2007
Done!
bra-serie-a
2008
Done!
bra-serie-a
2009
Done!
bra-serie-a
2010
Done!
bra-serie-a
2011
Done!
bra-serie-a
2012
Done!
bra-serie-a
2013
Done!
bra-serie-a
2014
Done!
bra-serie-a
2015
Done!
bra-serie-a
2016
Done!
bra-serie-a
2017
Done!
bra-serie-a
2018
Done!
bra-serie-b
2011
Done!
bra-serie-b
2012
Done!
bra-serie-b
2013
Done!
bra-serie-b
2014
Done!
bra-serie-b
2015
Done!
bra-serie-b
2016
Done!
bra-serie-b
2017
Done!
bra-serie-b
2018
Done!

In [22]:
final_dataframe.sample(5) # amostra com 5 linhas do dataframe

       pos              team  ...              league     season
60994   11     FC Schalke 04  ...          bundesliga  2016-2017
45786    7  AS Saint-Étienne  ...         fra-ligue-1  2016-2017
6586     7   Birmingham City  ...  eng-premier-league  2003-2004
58858   17   1899 Hoffenheim  ...          bundesliga  2012-2013
49125    4     VfL Wolfsburg  ...          bundesliga  1997-1998

[5 rows x 18 columns]

In [23]:
final_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104616 entries, 0 to 104615
Data columns (total 18 columns):
pos                        104616 non-null int64
team                       104616 non-null object
current_round              104616 non-null int64
max_rounds                 104616 non-null int64
rounds_left                104616 non-null int64
win                        104616 non-null int64
loss                       104616 non-null int64
draw                       104616 non-null int64
goals_for                  104616 non-null int64
goals_against              104616 non-null int64
goals_diff                 104616 non-null int64
goals_for_against_ratio    104616 non-null float64
points_for                 104616 non-null int64
possible_points            104616 non-null int64
total_possible_points      104616 non-null int64
performance                104616 non-null float64
league                     104616 non-null object
season                     104616 non-null object
dtypes: float64(2), int64(13), object(3)
memory usage: 14.4+ MB

In [0]:
df = add_final_points(final_dataframe)

In [28]:
df.sample(5)

     pos                 team  ...     season  final_points
110   11        Real Sociedad  ...  2013-2014            59
469   10  Deportivo La Coruña  ...  2004-2005            51
457   18          Flamengo RJ  ...       2013            45
87     8        Real Zaragoza  ...  2009-2010            41
220    1             Juventus  ...  2014-2015            87

[5 rows x 19 columns]

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 104616 entries, 0 to 759
Data columns (total 19 columns):
pos                        104616 non-null int64
team                       104616 non-null object
current_round              104616 non-null int64
max_rounds                 104616 non-null int64
rounds_left                104616 non-null int64
win                        104616 non-null int64
loss                       104616 non-null int64
draw                       104616 non-null int64
goals_for                  104616 non-null int64
goals_against              104616 non-null int64
goals_diff                 104616 non-null int64
goals_for_against_ratio    104616 non-null float64
points_for                 104616 non-null int64
possible_points            104616 non-null int64
total_possible_points      104616 non-null int64
performance                104616 non-null float64
league                     104616 non-null object
season                     104616 non-null object
final_points               104616 non-null int64
dtypes: float64(2), int64(14), object(3)
memory usage: 18.5+ MB

In [30]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
df.to_csv('/content/drive/My Drive/machine_learning_football_club/all_leagues_seasons.csv', sep=';', index=False)